- block:
  - name: Create distribution
    uri:
      url: "http://{{ pulp_api_host }}:{{ pulp_api_port }}/pulp/api/v3/distributions/ansible/ansible/"
      method: POST
      body:
        base_path: "{{ main_item.base_path }}-{{ 10000 | random }}"
        name: "{{ main_item.name }}-{{ 10000 | random }}"
        repository: "http://{{ pulp_api_host }}:{{ pulp_api_port }}{{ repository_created_response.json.pulp_href }}"
      body_format: json
      user: "{{ pulp_admin_username }}"
      password: "{{ pulp_default_admin_password }}"
      force_basic_auth: yes
      status_code: 202
    register: distribution_created_response
    run_once: true

  - name: Wait until the distribution task is complete
    uri:
      url: "http://{{ pulp_api_host }}:{{ pulp_api_port }}{{ distribution_created_response.json.task }}"
      user: "{{ pulp_admin_username }}"
      password: "{{ pulp_default_admin_password }}"
      force_basic_auth: yes
    register: distribution_created_task_response
    until: distribution_created_task_response.json.state != 'waiting'
    delay: 2
    retries: 60

  - debug:
      msg: "Task for creating distribution did not reach a successful state. {{ distribution_created_task_response }}"
    when: distribution_created_task_response.json.state != 'completed'
  when: repository_exists_response.json.count == 0
